### ISSUE TITLE
Adding other NPC quests? (Kenneth, Nepheli)

### ISSUE THREAD

**Issue by clicksilver** [Gobluebro/Elden-Ring-Checklist#1]
Are you taking contributions to adding more questlines for this? I figure it would be easy enough to transcribe the stuff from the wiki as people discover it into this tool. It's really awesome, thanks!

**Comment by Gobluebro** [comment]
Yes contributions are welcome. Feel free to fork this project and submit a pull request. 

[The data for this is located here](https://github.com/Gobluebro/Elden-Ring-Checklist/tree/main/data)
Each data file has the structure of 

```js
{
    id: "insert GUID here",
    name: "Insert Name Here",
    requirements: [
      {
        id: "insert GUID here",
        description: "Describe requirement here",
      },
      ...
    ]
},
```

Currently I generally try to summarize quest requirements in my own words from watching youtube videos on the quest line. I try to limit the amount of spoilers as hard as that is. I don't really go into a lot of detail as to describe everything you need to do for a requirement like how to find someone or the path you need to go step by step to get to the place you need to go. This checklist currently is just to help you keep your progress with quests. It shouldn't be a game guide.

But all that being said if you wish to contribute just give it your best judgement and I'll make any required last minute changes.

Thank you!

**Comment by clicksilver** [comment]
> It shouldn't be a game guide.

Gotcha, so it sounds like general rules of thumb are:

1. no specifics (coordinates, directions, etc)
2. describe steps as events as simply as possible

If I make a PR we can workshop how much is too much detail in the comments then

**Comment by Gobluebro** [comment]
Yep you got it perfectly!

Some things I forgot to mention is just how I try to write certain actions the same generally. That way actions are generally treated with the same directions.

interacting with characters I use "Talk to (x)"

killing a boss I use "Defeat (x)"

if there is dialogue options I use "Select the "(x)" dialogue option."

if grace sites are very close by then I generally include "at the (x) grace".

If you could write things that way I would greatly appreciate it. Thank you!

Also you don't need to include GUIDs if you find yourself doing a lot to generate them. I have an addon in VSCode that I can just general them all at once so you can leave them as `id: ""` and I'll add them myself once the PR is merged.
