### ISSUE TITLE
Morgott must be defeated before the throne room

### ISSUE THREAD

**Issue by JustAnOkapi** [Gobluebro/Elden-Ring-Checklist#10]
For the Nepheli and Kenneth quests I'd put a (Morgott must be defeated) for their last step.
> You can find Nepheli, Kenneth and Gostoc in the Stormveil Castle throne room near the [Godrick the Grafted](https://eldenring.wiki.fextralife.com/Interactive+Map?id=1129&lat=-173.910938&lng=85.500353&zoom=8&code=mapA) site of grace. 
Prerequisites: [Morgott](https://eldenring.wiki.fextralife.com/Morgott+the+Omen+King) must be defeated before all 3 NPCs can appear in the throne room.

**Comment by Gobluebro** [comment]
Sounds good to me

**Comment by Gobluebro** [comment]
Added it [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/adf1ccf99863a143c22e8763cb0d10c59d9625cd)
