### ISSUE TITLE
Link for a boss leads to the wrong wiki page.

### ISSUE THREAD

**Issue by GifanTheWoodElf** [Gobluebro/Elden-Ring-Checklist#100]
The boss fight for "Crucible Knight & Misbegotten Warrior" in Redmane links to the crucible knight wiki page, but there's a page specifically for this duo fight: https://eldenring.wiki.fextralife.com/Crucible+Knight+and+Misbegotten+Warrior

**Comment by Gobluebro** [comment]
updated thanks!
