### ISSUE TITLE
Missing Fallen Ruins of the Lake grace

### ISSUE THREAD

**Issue by 13xforever** [Gobluebro/Elden-Ring-Checklist#11]
Near the Raya Lucaria there's a grace that's not on the checklist 

![Fallen Ruins of the Lake Grace](https://user-images.githubusercontent.com/36445/162632804-e67addeb-9d9e-4f25-906c-bc5df1beab5b.png)

**Comment by Gobluebro** [comment]
Yes you are correct. I can add it where yours is currently but I'll probably go back and get all of the graces again there on my playthrough to get the correct location it appears in game

**Comment by Gobluebro** [comment]
Added the grace [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/8c3d5a5082b508ac795dd77d0d15ad38f77cd934)

**Comment by Gobluebro** [comment]
I believe this is the correct placement

![image](https://user-images.githubusercontent.com/14102413/162643714-9ec3d520-6b21-4502-91a2-d42a0452bcaa.png)

**Comment by Gobluebro** [comment]
Fixed [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/adcb8ad6ce6b4353a5b30249ce81792ea469ce30)
