### ISSUE TITLE
Add East Gate Bridge Trestle Grace

### ISSUE THREAD

**Issue by 13xforever** [Gobluebro/Elden-Ring-Checklist#12]
It's another missing grace near Raya Lucaria

![image](https://user-images.githubusercontent.com/36445/163630346-5fc28721-9e85-488e-9398-542157af71de.png)

**Comment by Gobluebro** [comment]
Confirmed location is here
![image](https://user-images.githubusercontent.com/14102413/163635721-8c529974-0941-41c2-b5a3-de7ae7179506.png)

**Comment by Gobluebro** [comment]
Added [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/39b7fb2d44ffa49470639f6953ee3ae0a4894137)

**Comment by Gobluebro** [comment]
thank you
