### ISSUE TITLE
Missing Onyx Lord boss

### ISSUE THREAD

**Issue by 13xforever** [Gobluebro/Elden-Ring-Checklist#13]
There are two Onyx Lord bosses in the game, one is in Liurnia (missing; at the [Royal Grave Evergaol](https://eldenring.wiki.fextralife.com/Onyx+Lord)), and the second one is in Leyndell.

**Comment by Gobluebro** [comment]
This one is pretty interesting. 

So upon further research this one in Liurnia was actually previously named "Alabaster Lord" 

See the comments on this page https://eldenring.wiki.fextralife.com/Alabaster+Lord 

and this example youtube video with the previous name https://www.youtube.com/watch?v=CX0pqP43ppE

Currently this is in the bosses section in Liunia as its previous name

```js
{
    id: "b08f4c29-6b2a-40a9-8369-8ff4aea3ef2a",
    description: "Alabaster Lord",
    url: "https://eldenring.wiki.fextralife.com/Alabaster+Lord",
},
```

I'll go ahead and update the changed name to reflect it.

**Comment by Gobluebro** [comment]
Renamed [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/cd27d3163e24f973028a3437a48fa28f561013ad)
