### ISSUE TITLE
Want to work together?

### ISSUE THREAD

**Issue by azy2** [Gobluebro/Elden-Ring-Checklist#15]
Hello. We have a similar project well in the works over at https://github.com/RoundtableHold/roundtablehold.github.io
Our site is https://roundtablehold.net if you want to check it out.

I was wondering if you wanted to come collaborate on our project in order to avoid duplicating work? We're trying to build a huge community driven site for Elden Ring and would love to work with you.

**Comment by Gobluebro** [comment]
Hello. Thanks but I am too busy to work on your project as well. While our projects are similar, I think we are both trying to provide different things. Good luck with your project though!

**Comment by JustAnOkapi** [comment]
> Though I want to preface this as, this website is not supposed to be the same as that website. I'm not going to be making a game guide like that website does where it tells you where to go in your play through to collect everything.
[Quote ](https://github.com/Gobluebro/Elden-Ring-Checklist/issues/5#issuecomment-1081053258)

**Comment by JustAnOkapi** [comment]
I think that @Gobluebro is trying to just have the checklist and not a full guide that explains everything, like your site?

**Comment by azy2** [comment]
We have both guides for those who want that, and checklists for just completionism. But I understand, these things take up a lot of time. I wish you luck.
