### ISSUE TITLE
Missing boss for Perfumer's Grotto in Altus Plateu

### ISSUE THREAD

**Issue by 13xforever** [Gobluebro/Elden-Ring-Checklist#16]
There's a twin [Miranda the Blighted Blom + Omenkiller](https://eldenring.wiki.fextralife.com/Perfumer's+Grotto) boss combo in the dungeon that's missing for Altus Plateu

**Comment by Gobluebro** [comment]
Unfortunately there is no wiki page for both, and currently for this checklist we only support one url. So I'm just going to go with the Miranda the Blighted Bloom boss link since it appears less to make sure it's not as confusing. Maybe one day I'll change it to be dangerously inserted html.

**Comment by Gobluebro** [comment]
Added [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/bee87eb9a8cc39f50c123c2a9f18b37ba2296edb)
