### ISSUE TITLE
Ancient Dragon Lansseax

### ISSUE THREAD

**Issue by 13xforever** [Gobluebro/Elden-Ring-Checklist#17]
He's on [Altus Plateau](https://eldenring.wiki.fextralife.com/Ancient+Dragon+Lansseax), near Rampartside Path grace, but on checklist it's listed in Mt. Gelmir section

**Comment by Gobluebro** [comment]
Refresh your browser. This was fixed [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/d50cce3845c533cf6248c7c76b8e6009a0755a84) 2 hours ago

**Comment by Gobluebro** [comment]
Alright I have synced the bosses up to date with this wiki page https://eldenring.wiki.fextralife.com/Bosses

Hopefully you will have more time to play the game instead of helping me fix this haha.

Thank you again for your help
