### ISSUE TITLE
Hermit Merchant's Shack is missing for Leyndell early game

### ISSUE THREAD

**Issue by 13xforever** [Gobluebro/Elden-Ring-Checklist#18]
It's certainly is there in the Outskirts
![image](https://user-images.githubusercontent.com/36445/164980879-01951fe1-f6bd-469e-8e2d-396597caeb8c.png)

**Comment by Gobluebro** [comment]
Added [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/54ed0830619ef96cf322f80fecf84c335ae42bb4) thank you
