### ISSUE TITLE
Black Blade Kindred is listed twice

### ISSUE THREAD

**Issue by 13xforever** [Gobluebro/Elden-Ring-Checklist#19]
Once under the Mountaintops of the GIants, and once under the Forbidden Lands (misspelled). There's only one [Black Blade Kindred](https://eldenring.wiki.fextralife.com/Black+Blade+Kindred) in this area.

**Comment by Gobluebro** [comment]
Good catch. Changed [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/53e6d695f057880f8d1116d392fae5ce49567b40).
