### ISSUE TITLE
East Capital Rampart grace is missing for late game

### ISSUE THREAD

**Issue by 13xforever** [Gobluebro/Elden-Ring-Checklist#21]
It is listed under Leyndell Outskirts for early game, but in late game it should probably be under the Leyndell, Ashen Capital
![image](https://user-images.githubusercontent.com/36445/166328712-2be0555e-cc9b-41a2-acb6-653a031abedb.png)

**Comment by Gobluebro** [comment]
I'm trying to keep my save stuck in early game for future confirmations. So I'm going to take your word for end game graces. Please let me know if you find anymore. Thanks

**Comment by Gobluebro** [comment]
Note this grace exists for both early and end game

**Comment by Gobluebro** [comment]
Added [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/be04448a02aff9cfc9bc98611d086cb59381da13)
