### ISSUE TITLE
I believe this is the last missing grace

### ISSUE THREAD

**Issue by 13xforever** [Gobluebro/Elden-Ring-Checklist#22]
Fractured Marika under the Stone Platform section is the endgame grace

![image](https://user-images.githubusercontent.com/36445/166339422-1e4eb015-ae7e-46a5-8028-ea44b6528344.png)

**Comment by Gobluebro** [comment]
Thanks, added [in this commit.](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/6fc1a2c0d67936d1052862cdd6a969574da1876b)
