### ISSUE TITLE
D, Hunter of the Dead and Fia / Age of Duskborn ending missing

### ISSUE THREAD

**Issue by alex100awesome** [Gobluebro/Elden-Ring-Checklist#23]

**Comment by Gobluebro** [comment]
Hello

This missing quest line is on the roadmap to be completed. [Here is a link to see all quest lines currently missing](https://github.com/Gobluebro/Elden-Ring-Checklist#roadmap)

**Comment by alex100awesome** [comment]
Thanks for letting me know
