### ISSUE TITLE
Alabaster Lord is missing

### ISSUE THREAD

**Issue by Monstermel** [Gobluebro/Elden-Ring-Checklist#24]
This [boss](https://eldenring.wiki.fextralife.com/Alabaster+Lord) should be in the Liurna of lakes section, but it's not.

**Comment by Gobluebro** [comment]
duplicate of #13 

The once named Alabaster Lord in the [Royal Grave Evergaol](https://eldenring.wiki.fextralife.com/Royal+Grave+Evergaol) was renamed in some update to have the name Onyx Lord.
