### ISSUE TITLE
Update Map Link functionality

### ISSUE THREAD

**Issue by davvolun** [Gobluebro/Elden-Ring-Checklist#27]
Partly discussed on PR #25 

Idea is to update the map links to be styled nicely, fitting with the design, and with appropriate UI/UX.

Suggestion is to use the JSX.Element (types: `description: string | JSX.Element`) to allow inline links.

@Gobluebro I'm planning on doing this myself, but please insert any requirements/suggestions.

**Comment by Gobluebro** [comment]
Requested changes completed in 06caa17
