### ISSUE TITLE
Divine Bridge Golem incorrectly listed as boss

### ISSUE THREAD

**Issue by davvolun** [Gobluebro/Elden-Ring-Checklist#28]
Divine Bridge Golem is listed as a boss, but it's actually a non-respawning enemy.

See: https://eldenring.wiki.fextralife.com/Golem#divinebridgegolem

**Comment by davvolun** [comment]
Opened PR #29 to remove Divine Bridge Golem as a boss.

**Comment by Gobluebro** [comment]
It seems to be delisted from the [bosses page](https://eldenring.wiki.fextralife.com/Bosses) on the wiki as well so this is fine with them
