### ISSUE TITLE
website is buggy 

### ISSUE THREAD

**Issue by Panouflex** [Gobluebro/Elden-Ring-Checklist#30]
hello, 

the website is a little buggy.
I lost my tracking on the quests.
I'm using mozilla firefox 

thanks for your help,

regards
![image](https://user-images.githubusercontent.com/118927222/203615480-d8463be7-3b91-45db-9a11-874130a349a7.png)

**Comment by Gobluebro** [comment]
Not sure why your css looks that way as mine works just fine in firefox.

This website uses local storage api provided by the browser for saving your progress. There is no database connected to this that I would have to pay for. Nor is there a feature to download and upload your progress via json file or something like that.

I do not have any plan to create something like that at this time. I suggest saving your progress with a screenshot if this problem occurs often for you.

**Comment by Panouflex** [comment]
Very Strange , it works now
I created an Excel if it doesn’t Works again

Thx

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Griffin Strayer ***@***.***>
Envoyé : Friday, November 25, 2022 3:58:56 PM
À : Gobluebro/Elden-Ring-Checklist ***@***.***>
Cc : Panouflex ***@***.***>; Author ***@***.***>
Objet : Re: [Gobluebro/Elden-Ring-Checklist] website is buggy (Issue #30)


Not sure why your css looks that way as mine works just fine in firefox.

This website uses local storage api provided by the browser for saving your progress. There is no database connected to this that I would have to pay for. Nor is there a feature to download and upload your progress via json file or something like that.

I do not have any plan to create something like that at this time. I suggest saving your progress with a screenshot if this problem occurs often for you.
