### ISSUE TITLE
Sellen quest steps

### ISSUE THREAD

**Issue by Tom-Smith-95** [Gobluebro/Elden-Ring-Checklist#34]
Sellen's quest needs a bit of cleanup and rewriting.

These steps need to be removed since they are not necessary for her quest:
- Find the Academy Scroll and give it to Sellen.
- Find the Royal House Scroll and give it to Sellen.
- Find the Conspectus Scroll and give it to Sellen.

This step needs to be rewritten as such:
- Find Lusat near the Fort Faroth grace and get the Stars of Ruin spell. (current)
- Find Lusat in Sellia Hideaway and get the Stars of Ruin spell. (rewritten)

This steps needs to be rewritten and a new line added:
- Transplant Sellen's primal glintstone in the puppet in Seluvis' secret chamber. (new line)
- Talk to Sellen near the Ranni's Rise grace. (current)
- Talk to Sellen in her new body in Seluvis' secret chamber. (rewritten)

Instead of "Radahn's herald", I would write "Jerren" since that's his name.

Lastly, I have followed your steps as you have written them, but i never found Jerren near Sellen's body, so that might be out of order. You might have to first talk to Jerren near her body before transplanting her primal glintstone into the puppet in Seluvis's Secret Puppet Room. This does not break her quest, but it does skip a few steps.

**Comment by Gobluebro** [comment]
Thanks for double checking this. Give me some time to verify this. A lot of these quests don't always match up 1:1. At some point I was hoping to implement a note / optional system for these. Not everyone plays the game the same so progressing past certain parts can cause this to happen.

**Comment by Gobluebro** [comment]
>   Transplant Sellen's primal glintstone in the puppet in Seluvis' secret chamber. (new line)
>   Talk to Sellen near the Ranni's Rise grace. (current)
>   Talk to Sellen in her new body in Seluvis' secret chamber. (rewritten)

Merged this all into one since talking to her after using the primal glintstone didn't actually matter for the questline.

**Comment by Gobluebro** [comment]
> Lastly, I have followed your steps as you have written them, but i never found Jerren near Sellen's body, so that might be out of order. You might have to first talk to Jerren near her body before transplanting her primal glintstone into the puppet in Seluvis's Secret Puppet Room. This does not break her quest, but it does skip a few steps.

I'm just gonna leave the steps how they are, I'm not really trying to help people troubleshoot their questlines. Just trying to give people a place to remember where they left off on a quest. From all the sources I have seen, this is the recommended steps for this questline so that's all I can really do.

**Comment by Gobluebro** [comment]
> Find the Academy Scroll and give it to Sellen.
Find the Royal House Scroll and give it to Sellen.
Find the Conspectus Scroll and give it to Sellen.

removed in 214637d

**Comment by Gobluebro** [comment]
>This step needs to be rewritten as such:
Find Lusat near the Fort Faroth grace and get the Stars of Ruin spell. (current)
Find Lusat in Sellia Hideaway and get the Stars of Ruin spell. (rewritten)


Changed in c73832d

**Comment by Gobluebro** [comment]
changed a bit of details and removed the last rewards since they were based on assisting sellen and would not be collectible if you assisted Jerren.
