### ISSUE TITLE
Casual Greeting gesture is missing from Misc > Gestures checklist.

### ISSUE THREAD

**Issue by Aluerie** [Gobluebro/Elden-Ring-Checklist#35]
https://eldenring.wiki.fextralife.com/Gestures

"Casual Greeting" gesture is missing. 

![image](https://user-images.githubusercontent.com/33165440/226186341-94af35ea-0e67-41d4-9815-b0747fc74d11.png)

There are 47 gestures in the game but the list has 46 so I figured out the missing one.

**Comment by Gobluebro** [comment]
Thanks for checking. I'll add this soon. I have been thinking about removing all of the "Automatically received" emotes so it will have a lot more "missing" once that is committed.

**Comment by Gobluebro** [comment]
added in 9490c91

**Comment by Gobluebro** [comment]
removed automatically received gestures in 9490c91
