### ISSUE TITLE
Patches quest

### ISSUE THREAD

**Issue by Tom-Smith-95** [Gobluebro/Elden-Ring-Checklist#36]
This step is optional and not needed to progress his quest.

- Return to Rykard at his grace and give the Dancer's Castanets to Tanith.

It should have an (Optional) at the beginning. All you have to do to progress is simply reload the area and he'll be gone from the Castellan's Hall. I guess the devs expected people to give the castanets to Tanith, go back to the Shaded Castle, see that Patches is gone, and then go to Murkwater Cave.

**Comment by Gobluebro** [comment]
added the word "optional" in a35570b
