### ISSUE TITLE
Question: How to sync across devices

### ISSUE THREAD

**Issue by tienxu04** [Gobluebro/Elden-Ring-Checklist#40]
Hi, i came across your checklist and i cant thank you enough! this is a godsend. however, im mostly using a PC at work, and would like to ask if there is a way so i can sync the checked items when at work with those made when im home (on a Mac)

i understand it runs on local storage, but still want to ask. thank you

**Comment by Gobluebro** [comment]
Currently there is no official way to sync these, since there is no account and your settings are not stored in a database.

**Comment by Gobluebro** [comment]
If you are comfortable with using developer tools and using the console you could get these settings copied to your machine through setting the localstorage yourself.

I took some time to try to get this to work myself. This is no way a working perfect solution that I will maintain by any means but merely proof you can technically copy the settings manually if you so wish.

On the computer you want to copy settings from:
```js
const json = JSON.stringify(Object.entries(localStorage));
```
Copy this string and save it however you want to get it to your other computer. It's a long string so I'd suggest something like a txt file.

On the computer you want to copy your settings over to:
```js
const backFromJSON = JSON.parse(**YOUR COPIED JSON STRING HERE**)

for(let i = 0; i < backFromJSON.length; i++){
    localStorage.setItem(backFromJSON[i][0], backFromJSON[i][1])
}
```

**Comment by Gobluebro** [comment]
You could probably do something like stringify on localstorage object itself and then loop through `Object.entries(theObject)` and plug them into localstorage that way as well.

Up to you.

Also I wish I could play elden ring at work 😂

**Comment by tienxu04** [comment]
thank you so much for your kind and dedicate reply. No, im not able to play at work either. i just make use of some free time there researching the game :)
