### ISSUE TITLE
Diallos Haslow Quest missing steps

### ISSUE THREAD

**Issue by SehrLeer** [Gobluebro/Elden-Ring-Checklist#41]
After you first meet him in the Roundtable Hold.

- Meet him in the western part of the academy gate town. [Map Link](https://eldenring.wiki.fextralife.com/Interactive+Map?id=6128&lat=-143.0156&lng=68.55965&zoom=8&code=mapA)
- Meet him in the Roundtable Hold

Thanks for all the work on this, it's been really helpful.

**Comment by Gobluebro** [comment]
This is talking about the very first part of the quest right?

These quests follow this order
https://eldenring.wiki.fextralife.com/Diallos

1. "Talk to Diallos at the Roundtable Hold."
2. "Talk to Diallos in Northern Liurnia near the Academy Gate Town Site of Grace."

These are basically what you said but just in the opposite order. 

Here are some videos confirming the same order as well:
[1.](https://www.youtube.com/watch?v=COA00lSSigU)
[2.](https://www.youtube.com/watch?v=SiT3T1kl4oM)
[3.](https://www.youtube.com/watch?v=WprMNqCNPTc)

**Comment by Gobluebro** [comment]
Gonna close this one unless evidence otherwise to change it.
