### ISSUE TITLE
Bell Bearings missing

### ISSUE THREAD

**Issue by 3bdNKocY** [Gobluebro/Elden-Ring-Checklist#43]
I'd like to add the Bell Bearings to the list but I was wondering where it would fit best as there are a few different types:
* merchant / npc
* smithing
* somber smithing
* glovewort
* ghost glovewort
* bell hunter

It can be put in a single list or split per type, which would impact where it would belong.
If it's in a single list, it might fit under "Misc", but that risks becoming a bit of a mess after a while.

What about having a "Collectibles" tab? It could contain the Whetblades, Bell Bearings, and in the future the Cookbooks.

**Comment by Gobluebro** [comment]
I don't mind a Collectibles tab. Honestly Misc could be renamed to Collectibles because what are Gestures if not something to collect.

**Comment by 3bdNKocY** [comment]
That's good to hear.
Any specific preference on how to organize the subsections, or is separating them all (i.e. 6 bell bearing subsections) good enough?

**Comment by Gobluebro** [comment]
Currently we don't support checklists inside of checklists. I'd say for now the best course is to just create them like 

- ghost glovework (1)
  - location
  - location
  - location
  - location
- ghost glovework (2)
- ghost glovework (3)

etc
