### ISSUE TITLE
It is possible to build an apk for this project?

### ISSUE THREAD

**Issue by LobaCW** [Gobluebro/Elden-Ring-Checklist#44]
Hi, I really liked your project and I think it would be cool to have it as an Android app so I could install it on my phone instead of using it in the browser.
I would like to know if this is feasible and, if so, how do I do it? I searched how to build this as apk in Android Studio, but I tried it without success. Could you explain what I need to do to build it as an apk or maybe share the apk online? I really appreciate that.

**Comment by Gobluebro** [comment]
Hey there. Thanks I'm glad you like the project. Unfortunately I do not know much about creating Android apps. So I can't be of much help here. This site is made with react for the browser.
