### ISSUE TITLE
Improvement: Import/Export Lists

### ISSUE THREAD

**Issue by NicmeisteR** [Gobluebro/Elden-Ring-Checklist#45]
Add the ability to export checklist or import it.
Been using the site on my phone and PC but also accidentally clicked one of the top checks and lost all my progress.

So being able to export (save) the current list as a backup would be a nice to have. (Also makes it sharable by friends)

Will look into implementing this soon.

**Comment by Gobluebro** [comment]
Hi check out issue #40 for some insight in how to do this. I worry about a possible issue where if any changes were made then the import data would be incompatible. Especially with the upcoming dlc I do expect more data to be added/changed.

**Comment by Gobluebro** [comment]
Added this functionality in 791eaef

Currently in beta testing for the time being.
