### ISSUE TITLE
Sacred Tears

### ISSUE THREAD

**Issue by b-rad41z** [Gobluebro/Elden-Ring-Checklist#46]
There is a section titled Golden Seeds which you can change to Flask Upgrades and add a section called Sacred Tears under it.

**Comment by Gobluebro** [comment]
Not currently possible to separate lists in a single tab.

Maybe possible to just combine into one tab called "Flask Upgrades" and then at the start of every item either say `Golden Seed - %location%` or `Sacred Tear - %location%`

**Comment by Gobluebro** [comment]
Added in 9c88017
