### ISSUE TITLE
Sync data across devices

### ISSUE THREAD

**Issue by prateeksingh19** [Gobluebro/Elden-Ring-Checklist#47]
I'll try adding a authentication process which will help in syncing data across multiple devices for a user. Will add database for saving user data.

This is take time and cant promise that i'll implement it, but, will try my best to do so.

**Comment by Gobluebro** [comment]
Hi. Thank you for your interest in this project.

> Will add database for saving user data.

This goes against the spirit of this project. The intent of this project was to have a quick, no login way to save your progress during your playthrough of elden ring.

You may fork this repo and add a database for your own purposes but I will not be paying the cost of hosting a database for the main project.
