### ISSUE TITLE
No spells/incantations checklist?

### ISSUE THREAD

**Issue by PinguWave** [Gobluebro/Elden-Ring-Checklist#48]
I just thought since weapons are in your checklist, users (including me) would also want to collect spells and incantations.
Thank you for your work.

**Comment by Gobluebro** [comment]
That is a reasonable request. 

I don't know if I want to make a whole tab for just two checklists of "Sorceries" and "Incantations".

Would the Misc tab be fine?

**Comment by Gobluebro** [comment]
Ended up going with a spells tab anyway, Will have to figure out what to do with the endless amount of tabs and how they display on all screen sizes.

**Comment by PinguWave** [comment]
Amazing! I sent you this first message before really starting my DLC prep and i now realize that i would also want to collect ashes of war and talismans. If you find the time to add those then i think your checklist will be perfect for anyone looking to fully prepare for the DLC. I recommend putting ashes of war in the spells tab and talismans in the collectables tab.

**Comment by Gobluebro** [comment]
> i would also want to collect ashes of war and talismans. If you find the time to add those then i think your checklist will be perfect for anyone looking to fully prepare for the DLC. I recommend putting ashes of war in the spells tab and talismans in the collectables tab.

I think that's probably a good idea. Talismans might be considered weapons, I'll have to look into it.

**Comment by Gobluebro** [comment]
@PinguWave Ashes of war and Talismans are now added
