### ISSUE TITLE
Missing: Nox Flowing Sword

### ISSUE THREAD

**Issue by trevorphillipscoding** [Gobluebro/Elden-Ring-Checklist#52]
Nox Flowing Sword is a Curved Sword that is missing from the list.

https://eldenring.wiki.fextralife.com/Nox+Flowing+Sword

**Comment by Gobluebro** [comment]
It was incorrectly added into the straight swords.

Moving it to the curved swords.

**Comment by Gobluebro** [comment]
Fixed in f44da8a

Thanks for finding this!
