### ISSUE TITLE
Import game's sl2 save file?

### ISSUE THREAD

**Issue by Nayzore** [Gobluebro/Elden-Ring-Checklist#55]
I don't believe I missed anything, but I apologize if I did. I assume you can only import/export the JSON saves from and for the website.

**Comment by Gobluebro** [comment]
I'm confused here. Are you talking about the website's import and export functionality? 

That is specifically to take your local storage from the progress you have made on this website. You could essentially take it to another computer or you could label them as your character's name for the json files itself and keep track of multiple characters.

I will not be implementing importing of sl2 files on the website.

**Comment by Gobluebro** [comment]
Changed the wording to hopefully bring less confusion in 8c7977f
