### ISSUE TITLE
Sorceress Sellen quest line missing a step

### ISSUE THREAD

**Issue by MrArkTen** [Gobluebro/Elden-Ring-Checklist#56]
I'm following this check list for a fresh play through and it's been great so far. I was stuck on Sellen's quest line for a while, she would'nt send me Witchbane Ruins where she is shackled. I just killed Radahn and the quest was able to progress. Maybe it could be added as a step. Thank you, great stuff.

**Comment by Gobluebro** [comment]
Thanks for suggestion. 
From the wiki https://eldenring.wiki.fextralife.com/Sorceress+Sellen
I can see that is a requirement

- Go back and speak with Sellen. She will give you a special glinstone key and task you with finding the sorcerer Master Lusat
- Return to Sellen after defeating [Starscourge Radahn](https://eldenring.wiki.fextralife.com/Starscourge+Radahn). She will request that you meet her in person at the [Witchbane Ruins](https://eldenring.wiki.fextralife.com/Witchbane+Ruins) where she will give you [Sellen's Primal Glintstone](https://eldenring.wiki.fextralife.com/Sellen's+Primal+Glintstone).

**Comment by Gobluebro** [comment]
Added in 4d7e3bf
