### ISSUE TITLE
Varre questline

### ISSUE THREAD

**Issue by Hrtkos** [Gobluebro/Elden-Ring-Checklist#57]
There are 3 additional steps in between "Gain access to the Roundtable Hold." and "Retrieve the Bravo! Gesture near The First Step grace."

1. (Optional) Talk to Varre again near The First Step grace. 
2. Earn Great Rune by defeating Godric the Grafted or any other shardbearer.
3. Talko to Enia at Roundhable Hold.

**Comment by Gobluebro** [comment]
Thanks for the suggestion.

From reading the wiki https://eldenring.wiki.fextralife.com/White+Mask+Varre I can see that is a missing requirement.
I can see that is the case. I'll fix it

**Comment by Gobluebro** [comment]
Added in fb41794
