### ISSUE TITLE
Missing "Fire's Deadly Sin" incantation (Base game)

### ISSUE THREAD

**Issue by Da-nie-elT** [Gobluebro/Elden-Ring-Checklist#58]
I don't see it in the list.
https://eldenring.fandom.com/wiki/Fire%27s_Deadly_Sin
https://eldenring.wiki.fextralife.com/Fire's+Deadly+Sin

**Comment by Gobluebro** [comment]
Good catch. It was not on [fextralife's incantations page](https://eldenring.wiki.fextralife.com/Incantations) so this site didn't have it either.

**Comment by Gobluebro** [comment]
Added in b784e2f
