### ISSUE TITLE
Ashes of War issues under Spells

### ISSUE THREAD

**Issue by thereseLYR** [Gobluebro/Elden-Ring-Checklist#59]
Some data is missing or inappropriately ordered.
1) "Giant Hunt" Ash of War (AoW) is listed at the end of the list, instead of being alphabetically ordered like everything else.
![image](https://github.com/Gobluebro/Elden-Ring-Checklist/assets/47405262/83af7d10-ad2c-4ef1-bc00-40617d747ff2)

2) "Blood Tax" AoW is missing entirely from the list.

**Comment by Gobluebro** [comment]
Thanks for finding and fixing this!
