### ISSUE TITLE
a good tool for boss and site marking

### ISSUE THREAD

**Issue by JustAnOkapi** [Gobluebro/Elden-Ring-Checklist#6]
[https://github.com/Zabuzard/EldenRingInteractiveMapItemProgression](https://github.com/Zabuzard/EldenRingInteractiveMapItemProgression)

**Comment by Gobluebro** [comment]
Hello

Thank you for this tool. I agree it is a good tool.

However, I don't think this is an appropriate use of the issues section of this repo. 

I've gone ahead and added a [contributing.md](https://github.com/Gobluebro/Elden-Ring-Checklist/blob/main/CONTRIBUTING.md) file for more detailed information on creating an issue/contributing.

In the future please try to keep issues related to this repo.

Thank you.
