### ISSUE TITLE
Missing Limgrave Site of Grace

### ISSUE THREAD

**Issue by Hautemeal** [Gobluebro/Elden-Ring-Checklist#61]
Deathtouched Catacombs Site of Grace is missing.

Thanks for this btw!

**Comment by Gobluebro** [comment]
Yeah no worries. I believe the graces specifically are ordered by how they appear in game. That's why it's under the sub region.

Thanks the effort of reaching out to help make this project better

**Comment by Hautemeal** [comment]
That makes sense. I also noticed that Mistwood is a subregion, but doesn’t have its own section like others. But at least the categories are all sorted by in-game distance to each other, so it’s not a big deal once you figure that out. I’m on my first NG+ run and finding this guide super helpful. Cheers!On Jun 26, 2024, at 9:10 AM, Griffin Strayer ***@***.***> wrote:﻿
Yeah no worries. I believe the graces specifically are ordered by how they appear in game. That's why it's under the sub region.
Thanks the effort of reaching out to help make this project better

**Comment by Gobluebro** [comment]
You might be into something here. I'll check what my in game says and compare it to what's written down here

**Comment by Hautemeal** [comment]
It seems like a very minor inconsistency since it would only be two or three sites of grace. And it’s debatable whether any of those are actually *in* the Mistwoods, or if they’re just outskirts of it, but they are all down there on the same plane. For consistency’s sake, it might make sense to have them be under a Mistwood category, but I think I may also be of the opinion that too many categories with 1-3 locations adds unnecessary clutter, but there are definitely pros and cons to each method. One refines the searchability and the other adds hierarchy clutter. Just my two cents as I’m using it for the first time. But, as I’m using it, I do find that the subregion method makes sense and is helpful, even if I’ve never thought to break it down that way. Anyway, thanks again for the response and actively working on this! On Jun 26, 2024, at 10:26 AM, Griffin Strayer ***@***.***> wrote:﻿
Reopened #61.

**Comment by Gobluebro** [comment]
I think originally it was modeled off of what the wiki would say about the grace and they had their own classifications of what region each grace was in.

But I think for completionist's sake it should probably be exactly how the game shows it when you open the menu. That way you can immediately know whether or not if you are missing graces.

**Comment by Hautemeal** [comment]
Ah! Now THAT’S a great idea. On Jun 26, 2024, at 2:21 PM, Griffin Strayer ***@***.***> wrote:﻿
I think originally it was modeled off of what the wiki would say about the grace and they had their own classifications of what region each grace was in.
But I think for completionist's sake it should probably be exactly how the game shows it when you open the menu. That way you can immediately know whether or not if you are missing graces.

**Comment by Gobluebro** [comment]
![image](https://github.com/Gobluebro/Elden-Ring-Checklist/assets/14102413/88d69f8a-bae1-4311-b0ee-223cc63fcead)
Are you seeing something different in your game? I had to go quickly grab the grace in my ng+ to check but I'm seeing Stormhill

**Comment by Hautemeal** [comment]
Same, I’m very early into my first NG+, but, yeah, that all matches what I have at the moment (plus Limgrave Divine Tower).On Jun 26, 2024, at 2:43 PM, Griffin Strayer ***@***.***> wrote:﻿
image.png (view on web)
Are you seeing something different in your game? I had to go quickly grab the grace in my ng+ to check but I'm seeing Stormhill

**Comment by Gobluebro** [comment]
Awesome glad we checked that

**Comment by Hautemeal** [comment]
Same. Thanks for being a cool nerd!
