### ISSUE TITLE
Requesting changes for the Collectables tab

### ISSUE THREAD

**Issue by CraneLaBell** [Gobluebro/Elden-Ring-Checklist#65]
I think that it would be a great change if you changed the talismans page to include +1 and +2 variants of the talismans to make it more effiecent on which ones you have and don't have. I also think it would be a good idea to add a section for the cracked tears, just a small thing that I thought would be a good idea. :) Oh also i just found that in the talismans tab some of the DLC talismans are showing even if the DLC hide tab is being used.

**Comment by Gobluebro** [comment]
That sounds like a good idea. It will take some time for the +1 +2 variants

**Comment by ashemedai** [comment]
Added a bunch of the +1/+2 talismans from the base game in #69. I might have missed one or two, although I hope not.

I kept the links to the base wiki page, since that's where they tend to be gathered at Fextralife.

**Comment by CraneLaBell** [comment]
Wonderful! I’m glad my idea was useful to you! I’ll be sure to double check the list to make sure you didn’t miss anything! 😁

**Comment by Gobluebro** [comment]
> I’ll be sure to double check the list to make sure you didn’t miss anything! 😁

Thank you that will be very helpful

**Comment by Gobluebro** [comment]
I should have added the remainder plus variants in e6892ee (including DLC variants). I am still missing the rest of the DLC talismans currently.

Let me know if I am missing any of the plus variants.

**Comment by Gobluebro** [comment]
Crystal tears added in 9287234

**Comment by Gobluebro** [comment]
I believe that covers everything, feel free to reopen this issue or create a new issue if you find anything missing.
