### ISSUE TITLE
More Collectables

### ISSUE THREAD

**Issue by DanyBoyP123** [Gobluebro/Elden-Ring-Checklist#66]
Have you considered adding Cracked Pots / Ritual Pots / Perfume Bottles ?
I usually collect those on every playthrough and I always end up wondering which ones I'm missing.

**Comment by Gobluebro** [comment]
Sure that seems feasible. I'll add it to the list of todos

**Comment by ashemedai** [comment]
I did an initial version for perfume bottles in #68 - not fully tested and unsure if this is the format that would be the most helpful. Also doesn't include the DLC changes as I have not been able to get to it yet.

**Comment by Gobluebro** [comment]
Perfume Bottle (Key item of the base game) added in b8ae803

**Comment by ashemedai** [comment]
Ritual pots via #71

**Comment by Gobluebro** [comment]
#71 (Ritual pots) has been merged.

**Comment by Gobluebro** [comment]
@ashemedai I wouldn't worry too much about alphabetical sorting at the moment. I usually end up copy and pasting the stuff that needs sorting alphabetically into a javascript console and running a sort on the names. I think quantity > quality in favor of more content is better than worrying about alphabetical. 

The only time I would ever consider thinking about placement of items is ordering collectables by when you can get them (based on zone level) is better than alphabetically naming. I think you have been doing that for every PR I have seen where that would be required though.

**Comment by ashemedai** [comment]
> @ashemedai The only time I would ever consider thinking about placement of items is ordering collectables by when you can get them (based on zone level) is better than alphabetically naming. I think you have been doing that for every PR I have seen where that would be required though.

Yeah, based on my own playthroughs, and what I have seen of others plus the relative strength of enemies, I have been trying to sort the collectables when most people would probably find and collect them.

**Comment by Gobluebro** [comment]
I checked the gestures in game and they are not sorted alphabetically, nor is there a way to sort them by such. I believe they are currently in the same order as they are in game (besides the ones you automatically receive). But the DLC order is not the same as shown on the [wiki ](https://eldenring.wiki.fextralife.com/Gestures) Hopefully someone could provide some screenshots for their order at some point

**Comment by Gobluebro** [comment]
Everything in this request has now been added. Hefty Cracked Pots are from the DLC and still not added
