### ISSUE TITLE
Night's Cavalry in Limgrave

### ISSUE THREAD

**Issue by 13xforever** [Gobluebro/Elden-Ring-Checklist#7]
There are two field bosses of this type in limgrave: one on the bridge to the west limgrave and one on the weeping peninsula, so the checklist should feature both for consistency with other similar bosses such as death bird

**Comment by Gobluebro** [comment]
Adding wiki link for confirmation.
https://eldenring.wiki.fextralife.com/Night's+Cavalry

Yes that is correct. I have gone ahead and added the second night's cavalry [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/2cdf6e77a908cfd37814c5cef818a761bfd51322).

Thanks

**Comment by Gobluebro** [comment]
Went back through all night's cavalry and double checked. Added the missing cavalry [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/65a3b93bcf4c0b250f9a52301638d32f651e2b9f)
