### ISSUE TITLE
Missing a couple things

### ISSUE THREAD

**Issue by 4sianMan** [Gobluebro/Elden-Ring-Checklist#74]
Missing shields, spirit ashes and armours

**Comment by Gobluebro** [comment]
I'll add them to the list of todos. Thanks

**Comment by Gobluebro** [comment]
Shields have been added

**Comment by Gobluebro** [comment]
Spirit Ashes have been added

**Comment by 4sianMan** [comment]
thx

**Comment by 4sianMan** [comment]
any progress on the armours?

**Comment by Gobluebro** [comment]
> any progress on the armours?

No, I will update this once progress has been made
