### ISSUE TITLE
Half an idea for DLC content

### ISSUE THREAD

**Issue by DanyBoyP123** [Gobluebro/Elden-Ring-Checklist#78]
I was thinking, for DLC regions, maybe you could change the color green to something else. It would make it clearer what is from the main game and what isn't. I'm just not sure how to handle stuff like new weapons in existing categories... Anyway, it's more of a thought than a request, what do you think ?

**Comment by Gobluebro** [comment]
Is this specifically for when DLC is mixed along with base game content? That does make sense to distinguish them in some way. Let me think about it

**Comment by Gobluebro** [comment]
> "*" at the end of the line

I am worried about users not knowing what this means. I tried doing something like that but I'm not completely set on it yet 
![image](https://github.com/Gobluebro/Elden-Ring-Checklist/assets/14102413/dffc7970-29df-427c-be60-fff91bf7a1a7)

**Comment by Gobluebro** [comment]
> new region from the DLC, you could do something like this:
> ![image](https://private-user-images.githubusercontent.com/174157054/346249415-28348020-54ac-449a-bd29-097d8a263467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDM4NTksIm5iZiI6MTcyMDQwMzU1OSwicGF0aCI6Ii8xNzQxNTcwNTQvMzQ2MjQ5NDE1LTI4MzQ4MDIwLTU0YWMtNDQ5YS1iZDI5LTA5N2Q4YTI2MzQ2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwMTUyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjViZWQyOWJjNGI3ZjE1ODM2MTM3NmM2MDg1MzBlNWE1ZDI1ODhlODAwNjRmMjU3ZjRhYTQwMzQ0Zjk1YWVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OeRJukQj0LYQJZgLIHEAt_W9Fhq6Xiyor0aYhFoXvlw)

I think toggling on and off feels good enough usually. Maybe I should make a toggle to show the base game content. Might make it much more obvious. 

The use cases depend on the tab.

Quests tab: You are in that specific content either base or DLC.

Weapons tab: I'm assuming you are either checking these off one by one or you are coming to the site to go through each checkbox and see which ones you have and which ones you are missing. So showing DLC in that case feels more like it's a matter of do you have the content or not.

**Comment by Gobluebro** [comment]
Thought about this some more. Going to add a shadow of the erdtree color scheme and use that for both lists and items

**Comment by Gobluebro** [comment]
I have added a filter button in 695ec1a to hide all base game requirements. You may now toggle between showing base game and dlc. Do you believe this fixes the original issue you were having?
