### ISSUE TITLE
Caelid missing a boss

### ISSUE THREAD

**Issue by dporem** [Gobluebro/Elden-Ring-Checklist#81]
Hi,

You are missing the [Erdtree Avatar in Caelid](https://eldenring.wiki.fextralife.com/Erdtree+Avatar).

**Comment by Gobluebro** [comment]
Hello,

I think you might be confusing the Erdtree avatar with the [Putrid Avatar](https://eldenring.wiki.fextralife.com/Putrid+Avatar)

**Comment by dporem** [comment]
You are right, please close it :)

**Comment by Gobluebro** [comment]
Let me know if you have any other missing content on the website, thank you!
