### ISSUE TITLE
Queelign's Greatsword is a Heavy Thrusting Sword.

### ISSUE THREAD

**Issue by CandleStormz** [Gobluebro/Elden-Ring-Checklist#82]
Despite the name, Queelign's Greatsword is considered a Heavy Thrusting Sword but is currently in the Greatsword Weapon Category 😅

**Comment by Gobluebro** [comment]
[That seems to be the case](https://eldenring.wiki.fextralife.com/Queelign%27s+Greatsword). I'll change it

**Comment by Gobluebro** [comment]
Fixed in 5a831e9
