### ISSUE TITLE
Stray space for various shields

### ISSUE THREAD

**Issue by ashemedai** [Gobluebro/Elden-Ring-Checklist#85]
See

https://github.com/Gobluebro/Elden-Ring-Checklist/blob/5a831e9514839665d76a1431e61e3fc2e8cf7005/data/lists/weapons.ts#L1785

https://github.com/Gobluebro/Elden-Ring-Checklist/blob/5a831e9514839665d76a1431e61e3fc2e8cf7005/data/lists/weapons.ts#L1862

https://github.com/Gobluebro/Elden-Ring-Checklist/blob/5a831e9514839665d76a1431e61e3fc2e8cf7005/data/lists/weapons.ts#L2602

https://github.com/Gobluebro/Elden-Ring-Checklist/blob/5a831e9514839665d76a1431e61e3fc2e8cf7005/data/lists/weapons.ts#L2658

https://github.com/Gobluebro/Elden-Ring-Checklist/blob/5a831e9514839665d76a1431e61e3fc2e8cf7005/data/lists/weapons.ts#L2722

https://github.com/Gobluebro/Elden-Ring-Checklist/blob/5a831e9514839665d76a1431e61e3fc2e8cf7005/data/lists/weapons.ts#L2779

**Comment by Gobluebro** [comment]
Fixed in f64432d. Thanks!
