### ISSUE TITLE
Putrid Avatars

### ISSUE THREAD

**Issue by 13xforever** [Gobluebro/Elden-Ring-Checklist#9]
There's two Putrid Avatars in Caelid and one in the Mountaintops of the Giants (https://eldenring.wiki.fextralife.com/Putrid+Avatar).

Checklist only mentions one in Caelid right now.

**Comment by Gobluebro** [comment]
Added the additional putrid avatars and their locations next to their name [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/ad72e917bbd63d49c49cd183c99196d9a22b0c34)

Thanks again!

**Comment by 13xforever** [comment]
Thanks!! What about the mountaintops one? Is it not a mini-boss? I'm only in Caelid right now and can't check.

**Comment by Gobluebro** [comment]
Yes it is indeed a boss.

Here is a video on it for confirmation. https://www.youtube.com/watch?v=51Kixersx8w
