### ISSUE TITLE
Property missing in Viridian Amber Medallion +3

### ISSUE THREAD

**Issue by Josu-A** [Gobluebro/Elden-Ring-Checklist#92]
The Viridian Amber Medallion +3 talisman is missing the isDLC property.

https://github.com/Gobluebro/Elden-Ring-Checklist/blob/63893606137ede788b7ce9afb0a0d3cb3f45f804/data/lists/collectables.ts#L2274-L2280

**Comment by Gobluebro** [comment]
Thanks!
