### ISSUE TITLE
Duplicated graces ?

### ISSUE THREAD

**Issue by DanyBoyP123** [Gobluebro/Elden-Ring-Checklist#99]
I'm not sure if this is a bug or if I'm not understanding it correctly, but why is "Capital Outskirts (Early Game)" the same list as "Leyndell, Royal Capital (Late Game)" ?

**Comment by Gobluebro** [comment]
It's been a while but I'm pretty sure the title at least changes as the game progresses. If the graces remain the same and already collected then we could combine them
